-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgc8f6me2PEhLR2KQW
EygcIF1oZ7/alpA4WZws7o+/8WSgCgYIKoZIzj0DAQehRANCAAQZd0y2B9JFE0tu
lcqCTiWJjc6QkrJoInGnwgsQG/6t3M0AahwdzsyMxjrak/Lt/FTmuPvGng2CnTW2
/JcEVaqW
-----END PRIVATE KEY-----