-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQghkvcv7DZI1QP8a6x
spelaskNF3RavWWbDroWsQVr8oigCgYIKoZIzj0DAQehRANCAATVELeqe4EnOAfw
Fy6+2XviWmFrdPJPaBR4hxa4awqvy+A7+m0Uct92ONmBRnMREW1SN9RigkmbzkbB
Birv/Rpc
-----END PRIVATE KEY-----