fastlane_version "2.30.1"

default_platform :ios
require 'spaceship'

platform :ios do
  before_all do
    #ENV["FASTLANE_ITC_TEAM_ID"] = "122594872"
    #ENV["FASTLANE_TEAM_ID"] = "8G6S883BRT"
    #ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "ldlp-zxnj-svxq-wtyi"


  end

  desc 'Send metdata'
  lane :sendMetada do
    deliver(
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end

  desc 'Delete sandbox users'
  lane :test_testers do |options|
    require 'pp'
    require 'spaceship'

    Spaceship::Tunes.login(options[:email])
    Spaceship::Tunes.select_team(team_name: 'BGTECH LTD')

    testers = Spaceship::ConnectAPI::SandboxTester.all
    pp testers

    testers.each do |tester|
      if UI.confirm("Delete #{tester.email}?")
        tester.delete!
      end
    end
  end

  desc 'Crete user in sandbox'
  lane :create_testers do |options|
    require 'pp'
    require 'spaceship'

    Spaceship::Tunes.login(options[:email])
    Spaceship::Tunes.select_team(team_name: 'BGTECH LTD')

    allTester = Spaceship::ConnectAPI::SandboxTester.all

    number = 0
    allTester.each do |tester|
      parts = tester.email.split('+')

      if parts.length() != 2
        UI.message("Wrong email #{tester.email}")
        next
      end

      secondParst = parts[1].split('@')

      if secondParst.length() != 2
        UI.message("Wrong second parts #{secondParst}")
        next
      end

      if secondParst[0].to_i > number
        number = secondParst[0].to_i
      end
    end

    emailSandbox = "testlill+#{number + 1}@geeks.com"
    pp emailSandbox

    tester = Spaceship::ConnectAPI::SandboxTester.create(
      first_name: "Test",
      last_name: "Three",
      email: emailSandbox,
      password: "199007()qQ",
      confirm_password: "199007()qQ",
      secret_question: "Question",
      secret_answer: "Answer",
      birth_date: "1980-03-01",
      app_store_territory: "USA"
    )
    pp tester
  end

  desc "Push to TestFlight"
  lane :test_flight do |options|
    #tag_name = options[:tag_name]
    #parts = tag_name.split('-')
    #if parts.length() != 2
      #UI.message("Wrong tag name #{tag_name}")
      #next
    #end
    #for pod install
    # cocoapods(
    #    clean_install: true,
    #    podfile: "./Podfile"
    # )
    #cocoapods(use_bundle_exec: false)
    build_app(workspace: "Lill.xcworkspace", configuration: "Release",  xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
